spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/links_service
    username: postgres
    password: 12345
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: short_link_service